Copied chorus to all parts, wrote another verse
NylonEric/RPP28-Jingle pull request #1
Opened 2021-02-13 01:15 UTC by saralandis

Let me know your thoughts on the verse..... 

Will write more verses if you let me!

2021-02-13 01:31 UTC, NylonEric requested changes
Thanks for the work. Take a look at the suggestions and see if you can tweak what you submitted. This is going to be fun!

2021-02-13 01:31 UTC, NylonEric commented on README.md
> +|She had not been two weeks from shore<br>When down on her a right whale bore<br>The captain called all hands and swore<br>He'd take that whale in tow (huh)| Our lives had been such bores<br>When we
We'll probably need a couple more syllables to match the pitches of the melody. ie 
She Had not been two weeks from shore
Our lives had been such ----  ----   bores

2021-02-13 01:31 UTC, NylonEric commented on README.md
> +|Soon may the Wellerman come<br>To bring us sugar and tea and rum<br>One day, when the tonguing' is done<br>We'll take our leave and go|LinkedIn decides our fate<br>Kitchen time, don't be late!<br>Pu
Thanks for adding the other chorues! Please feel free to write another verse, or tweek the chorus. I would like to match the "end-rhyming" of the original if possible, but I wanted to end with the "cohort twenty eight!"

end-rhyme of original chorus:
****** Come
****** Rum
****** Done
****** Go

2021-02-17 21:31 UTC, saralandis commented
I tweeked my chorus. Thoughts?

2021-03-01 21:52 UTC, merged

2021-03-01 21:52 UTC, NylonEric commented
Looks good, can you do one more verse?